/* â”€â”€ MOMENTS PANEL â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
const MOMENTS_DATA = [
  {id:1,passage:"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",book:"Pride and Prejudice",chapter:"Chapter 1",page:1,interpretation:"Austen opens with irony so sharp it cuts through two centuries. The truth is not universal at all — it is the projection of a society that reduces people to their economic utility."},
  {id:2,passage:"In my younger and more vulnerable years my father gave me some advice.",book:"The Great Gatsby",chapter:"Chapter 1",page:1,interpretation:"Nick wants us to think he is trustworthy — that he reserves judgment. But the entire novel is him judging everyone. The vulnerability he claims feels performed."},
  {id:3,passage:"Whenever you feel like criticizing anyone, remember that all the people in this world have not had the advantages that you have had.",book:"The Great Gatsby",chapter:"Chapter 1",page:1,interpretation:"His father's advice sounds compassionate, but there is a quiet elitism buried in it. Privilege speaking to privilege about being kind to the less privileged."},
  {id:4,passage:"There was no possibility of taking a walk that day.",book:"Jane Eyre",chapter:"Chapter 1",page:1,interpretation:"The entire book in one line. Jane's world is one of closed doors and denied freedoms. Yet that trapped energy is what eventually propels her forward. Constraint as catalyst."},
  {id:5,passage:"He had successfully avoided meeting his landlady on the staircase.",book:"Crime and Punishment",chapter:"Part I, Chapter 1",page:1,interpretation:null},
  {id:6,passage:"I never liked long walks, especially on chilly afternoons.",book:"Jane Eyre",chapter:"Chapter 1",page:1,interpretation:"A child who dislikes walks is a child who has no safe destination. This tiny preference reveals an entire emotional landscape."},
];
